### PR TITLE
Create generator-generic-ossf-slsa3-publish.yml

### PR DESCRIPTION
**Pull request by qna4dev**
Create generator-generic-ossf-slsa3-publish.yml

### CODE REVIEW

**Review by ezzak — CHANGES_REQUESTED** [review]
Can you please add context to what these changes do?

**Review by qna4dev — COMMENTED** [review]
.github/workflows/generator-generic-ossf-slsa3-publish.yml

**Review by qna4dev — COMMENTED** [review]
Create generator-generic-ossf-slsa3-publish.yml

**Comment by ezzak** [comment]
Asking again because this comment is unclear to me, can you please add context to what these changes do?

**Comment by ezzak** [comment]
Hi, this PR is still unclear to me.

Please feel free to re-open once you've answered the question above https://github.com/facebookincubator/meta-code-verify/pull/286#issuecomment-1845897368

**Pull request closed without merging**
